### ISSUE TITLE
Hardcoded network source

### ISSUE THREAD

**Issue by LucasGood** [mjdubell/SYN-Flooder#4]
I am running your tool on a `10.0.x.x` network and the source IP in both wireshark and your tool state that is sourced from `192.168.250.1`. 

I found in your code that the source IP (`192.168.250.1`) is hard coded.

Shouldn't this be defined automatically or via user input?
I have manually changed the source IP and found that 1 is consistently appended onto the source IP, eg `src_net = "10.0.1.55"` becomes source IP `10.0.1.551`. Removing the last 5 causes the source IP to `10.0.1.51`

**Comment by dubs3c** [comment]
Hello Lucas, thanks for opening an issue.

Actually, the variable `src_net` does not contain the full IP address, it's the *network* address. The value that is hardcoded is `192.168.250.` which only contains the network part of the IP address (this is a c-class network, /24 mask).

If you look here: https://github.com/mjdubell/SYN-Flooder/blob/master/syn_flooder.py#L54, it will build the full IP address with the value from the for loop, `src_host`.

The target will see this IP but wont be able to send anything to it, since in your case it's a total different network with no routes to it. But the purpose is to not have the target respond to anything, the purpose is just to spoof the source address to something else, and flood the target with requests.

If you want to change it anyway, set the following `src_net = 10.0.1.`. I assume that is correct for your network.

In any case, you are right that this value should be configured from the command line directly :) Maybe I'll update it later, unless you want to send a pull request ;)

**Comment by LucasGood** [comment]
Thanks for responding. 

I appreciate the explanation of your code. 

I was thinking firewalls could possibly interfere with SYN packets marked from a different or non-existent network. Plus, my OCD wanted to see those packets coming from the right network :smile: 

In an ideal world, this source IP would be automatically configured if no option to specify source IP was listed in the command, and an additional option would allow the user to specify source IP if wanted.

I'll play around with your code a bit and see if I can get it to work w/ user input. If that happens, I will hand in the code for review.

**Comment by dubs3c** [comment]
You are correct that a firewall could potentially block such requests :)

I guess one could get the current IP address from one of the active network cards and use the network part of the address as the base for spoofing the source IP addresses.

Quick question, how did you find this repository?

**Comment by LucasGood** [comment]
I found this repo via google. I wanted a tool that would generate SYN packets for me so I could experiment with my home network. This was the first tool I found.

**Comment by dubs3c** [comment]
Cool :)

**Comment by LucasGood** [comment]
FYI I have created a private Gitlab repository with a copy of your code so I can work on it there. Once I have a working version, I will let you know so you can create a new branch and start a QA process on any work I can complete.

**Comment by LucasGood** [comment]
@mjdubell I am ready to merge my fork back into this repo. Do you want to create a branch for me to merge into? If not, I can merge into master.

Thanks!

**Comment by dubs3c** [comment]
@LucasGood You can create a pull request and from there I can merge into master.

**Comment by dubs3c** [comment]
Once a PR comes in, I will review it and merge it.
